version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - POSTGRES_DB=career_vertex_db
      - POSTGRES_USER=vertex_user
      - POSTGRES_PASSWORD=vertexpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    command: gunicorn jobs.wsgi:application --bind 0.0.0.0:8000

  nginx:
    restart: always
    build: ./deployment/nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/key.pem:/etc/ssl/key.pem:ro
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem:ro
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    depends_on:
      - web

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=career_vertex_db
      - POSTGRES_USER=vertex_user
      - POSTGRES_PASSWORD=vertexpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  postgres_data:
