# Generated by Django 4.0.1 on 2024-06-22 08:28

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0014_alter_job_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title', 'location', 'created_at'), unique=True, verbose_name='slug'),
        ),
    ]
