name: CI/CD

on:
  push:
    branches:
      - version

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.UBUNTU_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/careervertex
            git pull origin version
            docker-compose -f docker-compose.prod.yml up --build -d